name: Continuous Deployment to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Install bundler
        run: gem install bundler:2.0.2
      - name: Install bundled gems
        run: bundle install
      - name: Build site
        run: bundle exec middleman build
      - name: Publish site
        uses: MikaelSmith/actions-gh-pages@fix-branching
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
