name: Continuous Deployment to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Install bundler
        run: gem install bundler:2.0.2
      - name: Install bundled gems
        run: bundle install
      - name: Configure git user email
        run: git config --global user.email "james@floehopper.org"
      - name: Configure git user name
        run: git config --global user.name "James Mead"
      - name: Build & publish site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec rake publish
