name: Continuous Deployment to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.6

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Update package lists
        run: apt-get update -qq
      - name: Install packages
        run: apt-get -yqq install nodejs
      - name: Install bundler
        run: gem install bundler:2.1.4
      - name: Install bundled gems
        run: bundle install
      - name: Build site
        run: bundle exec middleman build
      - name: Publish site
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: ./build
